apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: fareapplication
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: chuckbuckney/fare_app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fareapplicationservice
  namespace: fareapplication
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - port: 8080
      targetPort: 8080
#     nodePort: 32500